---
plan:
  name: Basic
  state: published
  setup_fee: 0.0
  cost_per_month: 0.0
  trial_period_days: 0
  cancellation_period: 0
  approval_required: false
  system_name: basic
limits: []
pricingrules: []
plan_features:
- name: Unlimited Greetings
  system_name: unlimited_greetings
  scope: application_plan
  visible: true
metrics: []
methods: []
created_at: '2020-05-20T08:53:38Z'
toolbox_version: 0.16.0
